version: '3.9'
services:
  dlc-link-attestor-1:
    image: public.ecr.aws/dlc-link/dlc-attestor:${ATTESTOR_VERSION}
    ports:
      - ${ATTESTOR_PORT}:8801
    environment:
      "PORT": "8801"
      # Supported chains: ETH_GOERLI, ETH_SEPOLIA, ETH_MAINNET, ETH_LOCAL
      "CHAIN_1": "ETH_GOERLI"
      "VERSION_1": "1"
      # This is the API key for the ETH_GOERLI chain (Infura)
      "API_KEY_1": ${INFURA_API_KEY}
      "STORAGE_API_ENABLED": "true"
      "STORAGE_API_ENDPOINT": ${STORAGE_API_ENDPOINT}
      "SECRET_KEY_FILE": "secret1.key"
      # Optional BRANCH: the branch in dlc-solidity repo to fetch deployment info from
      # Default: master
      "BRANCH": "attestor-manager"
